env:
  es6: true
  node: true
  mocha: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
rules:
<<<<<<< HEAD
  "comma-dangle": ["error", "never"]
=======
  "comma-dangle": ["error", "never"]
>>>>>>> master
