language: node_js
cache:
 directories:
 - node_modules
notifications:
 email: false
node_js:
- '7'
- '6'
branches:
 except:
<<<<<<< HEAD
 - /^v\d+\.\d+\.\d+$/
=======
 - /^v\d+\.\d+\.\d+$/
 
	>>>>>> a8af4ec958752c3af4294e5b56f53d47b2ba1236
